julia  src/run.jl data/p4.2.a.txt --cfg config/TOP.cfg &> out/p4.2.a.out
julia  src/run.jl data/p4.2.b.txt --cfg config/TOP.cfg &> out/p4.2.b.out
julia  src/run.jl data/p4.2.c.txt --cfg config/TOP.cfg &> out/p4.2.c.out
julia  src/run.jl data/p4.2.d.txt --cfg config/TOP.cfg &> out/p4.2.d.out
julia  src/run.jl data/p4.2.e.txt --cfg config/TOP.cfg &> out/p4.2.e.out
julia  src/run.jl data/p4.2.f.txt --cfg config/TOP.cfg &> out/p4.2.f.out
julia  src/run.jl data/p4.2.g.txt --cfg config/TOP.cfg &> out/p4.2.g.out
julia  src/run.jl data/p4.2.h.txt --cfg config/TOP.cfg &> out/p4.2.h.out
julia  src/run.jl data/p4.2.i.txt --cfg config/TOP.cfg &> out/p4.2.i.out
julia  src/run.jl data/p4.2.j.txt --cfg config/TOP.cfg &> out/p4.2.j.out
julia  src/run.jl data/p4.2.k.txt --cfg config/TOP.cfg &> out/p4.2.k.out
julia  src/run.jl data/p4.2.l.txt --cfg config/TOP.cfg &> out/p4.2.l.out
julia  src/run.jl data/p4.2.m.txt --cfg config/TOP.cfg &> out/p4.2.m.out
julia  src/run.jl data/p4.2.n.txt --cfg config/TOP.cfg &> out/p4.2.n.out
julia  src/run.jl data/p4.2.o.txt --cfg config/TOP.cfg &> out/p4.2.o.out
julia  src/run.jl data/p4.2.p.txt --cfg config/TOP.cfg &> out/p4.2.p.out
julia  src/run.jl data/p4.2.q.txt --cfg config/TOP.cfg &> out/p4.2.q.out
julia  src/run.jl data/p4.2.r.txt --cfg config/TOP.cfg &> out/p4.2.r.out
julia  src/run.jl data/p4.2.s.txt --cfg config/TOP.cfg &> out/p4.2.s.out
julia  src/run.jl data/p4.2.t.txt --cfg config/TOP.cfg &> out/p4.2.t.out
julia  src/run.jl data/p4.3.a.txt --cfg config/TOP.cfg &> out/p4.3.a.out
julia  src/run.jl data/p4.3.b.txt --cfg config/TOP.cfg &> out/p4.3.b.out
julia  src/run.jl data/p4.3.c.txt --cfg config/TOP.cfg &> out/p4.3.c.out
julia  src/run.jl data/p4.3.d.txt --cfg config/TOP.cfg &> out/p4.3.d.out
julia  src/run.jl data/p4.3.e.txt --cfg config/TOP.cfg &> out/p4.3.e.out
julia  src/run.jl data/p4.3.f.txt --cfg config/TOP.cfg &> out/p4.3.f.out
julia  src/run.jl data/p4.3.g.txt --cfg config/TOP.cfg &> out/p4.3.g.out
julia  src/run.jl data/p4.3.h.txt --cfg config/TOP.cfg &> out/p4.3.h.out
julia  src/run.jl data/p4.3.i.txt --cfg config/TOP.cfg &> out/p4.3.i.out
julia  src/run.jl data/p4.3.j.txt --cfg config/TOP.cfg &> out/p4.3.j.out
julia  src/run.jl data/p4.3.k.txt --cfg config/TOP.cfg &> out/p4.3.k.out
julia  src/run.jl data/p4.3.l.txt --cfg config/TOP.cfg &> out/p4.3.l.out
julia  src/run.jl data/p4.3.m.txt --cfg config/TOP.cfg &> out/p4.3.m.out
julia  src/run.jl data/p4.3.n.txt --cfg config/TOP.cfg &> out/p4.3.n.out
julia  src/run.jl data/p4.3.o.txt --cfg config/TOP.cfg &> out/p4.3.o.out
julia  src/run.jl data/p4.3.p.txt --cfg config/TOP.cfg &> out/p4.3.p.out
julia  src/run.jl data/p4.3.q.txt --cfg config/TOP.cfg &> out/p4.3.q.out
julia  src/run.jl data/p4.3.r.txt --cfg config/TOP.cfg &> out/p4.3.r.out
julia  src/run.jl data/p4.3.s.txt --cfg config/TOP.cfg &> out/p4.3.s.out
julia  src/run.jl data/p4.3.t.txt --cfg config/TOP.cfg &> out/p4.3.t.out
julia  src/run.jl data/p4.4.a.txt --cfg config/TOP.cfg &> out/p4.4.a.out
julia  src/run.jl data/p4.4.b.txt --cfg config/TOP.cfg &> out/p4.4.b.out
julia  src/run.jl data/p4.4.c.txt --cfg config/TOP.cfg &> out/p4.4.c.out
julia  src/run.jl data/p4.4.d.txt --cfg config/TOP.cfg &> out/p4.4.d.out
julia  src/run.jl data/p4.4.e.txt --cfg config/TOP.cfg &> out/p4.4.e.out
julia  src/run.jl data/p4.4.f.txt --cfg config/TOP.cfg &> out/p4.4.f.out
julia  src/run.jl data/p4.4.g.txt --cfg config/TOP.cfg &> out/p4.4.g.out
julia  src/run.jl data/p4.4.h.txt --cfg config/TOP.cfg &> out/p4.4.h.out
julia  src/run.jl data/p4.4.i.txt --cfg config/TOP.cfg &> out/p4.4.i.out
julia  src/run.jl data/p4.4.j.txt --cfg config/TOP.cfg &> out/p4.4.j.out
julia  src/run.jl data/p4.4.k.txt --cfg config/TOP.cfg &> out/p4.4.k.out
julia  src/run.jl data/p4.4.l.txt --cfg config/TOP.cfg &> out/p4.4.l.out
julia  src/run.jl data/p4.4.m.txt --cfg config/TOP.cfg &> out/p4.4.m.out
julia  src/run.jl data/p4.4.n.txt --cfg config/TOP.cfg &> out/p4.4.n.out
julia  src/run.jl data/p4.4.o.txt --cfg config/TOP.cfg &> out/p4.4.o.out
julia  src/run.jl data/p4.4.p.txt --cfg config/TOP.cfg &> out/p4.4.p.out
julia  src/run.jl data/p4.4.q.txt --cfg config/TOP.cfg &> out/p4.4.q.out
julia  src/run.jl data/p4.4.r.txt --cfg config/TOP.cfg &> out/p4.4.r.out
julia  src/run.jl data/p4.4.s.txt --cfg config/TOP.cfg &> out/p4.4.s.out
julia  src/run.jl data/p4.4.t.txt --cfg config/TOP.cfg &> out/p4.4.t.out
